# Node.js with React

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd react-ui/
    npm install
    npm run build
    cd ../server
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure SP Hackathon'
    appType: 'webAppLinux'
    WebAppName: 'foodshareap'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript